### ISSUE TITLE
About denying connections with a specific html file, again.

### ISSUE THREAD

**Issue by nmr50** [porech/caddy-maxmind-geolocation#10]
Hello ale-rinaldi, I'm sorry I went away for a months - so now I want to start the prev. topic - again.
OK, I have the same config file:
```
https://v4.site, https://v6.site {
        log {
                output file access.log
        }

        root * /home/tmh/caddy/web

        @blocked1 not maxmind_geolocation {
                db_path "/home/tmh/caddy/geolite/GeoLite2-Country.mmdb"
                allow_countries RU IL FR
        }
        rewrite @blocked1 def.html

        @blocked2 {
                path /home/tmh/caddy/web/private*
                not maxmind_geolocation {
                db_path "/home/tmh/caddy/geolite/GeoLite2-Country.mmdb"
                allow_countries RU
                }
        }
        rewrite @blocked2 def.html

        file_server
}

```
-- on mar'21 you told me about might-be incorrect rules in this scheme so - I want to ask you - how to fix this config so
it will redirect all users who are NOT listed in "RU IL FR" / "RU" countries - to the 'def.html' file ?

BTW, If you are IRC.LIBERA.CHAT or/and IRC.FREENODE.NET user - we can talk there in real time, so I'll be able to test the things and tell you results asap :)

Thanks in advance !
-t

**Comment by porjo** [comment]
This should work:
```
https://v4.site, https://v6.site {
	log {
		output file access.log
	}

	root * /home/tmh/caddy/web

	@blocked1 not maxmind_geolocation {
		db_path "/home/tmh/caddy/geolite/GeoLite2-Country.mmdb"
		allow_countries RU IL FR
	}

	error @blocked1 "Unauthorized" 403

	@blocked2 {
		path /home/tmh/caddy/web/private*
		not maxmind_geolocation {
			db_path "/home/tmh/caddy/geolite/GeoLite2-Country.mmdb"
			allow_countries RU
		}
	}

	error @blocked2 "Unauthorized" 403

	handle_errors {
		rewrite @blocked1 def.html
		rewrite @blocked2 def.html
		file_server
	}

	file_server
}
```

**Comment by nmr50** [comment]
porjo: Thanks for helping, but what I see now is "Error 403" and no redirects to def.html file at all... Any ideas ?:)

**Comment by porjo** [comment]
Does the file exist at `/home/tmh/caddy/web/def.html` with permission for Caddy to read it?

**Comment by nmr50** [comment]
ah, you right - def.html was located in ./caddy/ folder -- now I moved it to ./caddy/web/ folder and everything went OK !
Thank you very much, porjo, be well ! :)
