### ISSUE TITLE
Errors: the MaxMind DB file's data section contains bad data 

### ISSUE THREAD

**Issue by nateify** [porech/caddy-maxmind-geolocation#13]
On the latest version of this plugin and on Caddy v2.6.1 I am getting repeated errors that prevent me from accessing the site with a geofilter on, even though the IP address is in an allowed country. It shows a port for example, which I left uncensored but the IP itself is censored:

`{"level":"warn","ts":1664120226.9286664,"logger":"http.matchers.maxmind_geolocation","msg":"cannot lookup IP address","address":"XXX.XXX.XXX.XXX:63167","error":"the MaxMind DB file's data section contains bad data (uint32 size of 16)"}`

I can confirm the MMDB file I have is not corrupt, I can load it into a Python module capable of reading MMDB files, and I can further verify it recognizes the IP as being in the allowed country.

The issue is sometimes fixed by restarting Caddy but then occurs again sometime after when Caddy is left running. If It makes a difference, I am running on ARM64 architecture.

Here is a partially censored version of my Caddyfile:

```
(common) {
	encode zstd gzip

	header {
		Permissions-Policy interest-cohort=()
		Strict-Transport-Security "max-age=31536000; includeSubdomains;"
		X-Content-Type-Options nosniff
		X-Frame-Options DENY
		Referrer-Policy no-referrer
	}
}

(robots) {
	header {
		X-Robots-Tag "noindex, noimageindex, nofollow"
	}
	respond /robots.txt 200 {
		body "User-agent: *
Disallow: /"
	}
}

(geofilter) {
	@geofilter {
		not maxmind_geolocation {
			db_path "/usr/share/GeoIP/GeoLite2-Country.mmdb"
			allow_countries US
		}
	}
	handle @geofilter {
		abort
	}
}

*.example.com {
	tls {
		redacted
		}
	}
	@example2 host example2.example.com
	handle @example2 {
		import common
		import robots
		import geofilter

		reverse_proxy example2:8080
	}
}
```

Here is also a copy of the MMDB file I am using: https://send.zcyph.cc/download/8cd35379bc44bec8/#1ZOX3eOLY94gROSewM8HuA

**Comment by ale-rinaldi** [comment]
Hello @nateify , sorry I'm really late to the party.

I didn't update project dependencies for a while, including the libraries used to read the MMDB file. I now updated them to the latest version, can you please try a fresh build and see if this is fixed for you?

Thank you

**Comment by ale-rinaldi** [comment]
Hello,

I'm assuming this is fixed now, if it's not feel free to open a new issue!

Thanks
