### ISSUE TITLE
White list certain IPs/IP ranges in addition to geo blocking

### ISSUE THREAD

**Issue by allthesebugsv2** [porech/caddy-maxmind-geolocation#2]
Hi there and thanks for the plugin! I am allowing only IPs from a specific country with your plugin using this setup in my Caddyfile:
```
(GEOFILTER) {
        @geofilter {
                not maxmind_geolocation {
                        db_path "/usr/share/GeoIP/GeoLite2-Country.mmdb"
                        allow_countries FR
                }
        }
        respond @geofilter 403
}

my.domain.com {
        import GEOFILTER
        reverse_proxy local:7625
}
```
This seems to work fine and only allows French IPs. However, it also blocks local lan IPs and also IPs from my VPN. My question therefore is: how would I go about allowing certain IP ranges in addition to the geofilter directive? Unfortunately it is not really clear to me. Thank you for any help!

**Comment by allthesebugsv2** [comment]
Solution is here: https://caddy.community/t/white-list-certain-ips-ip-ranges-in-addition-to-geo-blocking/12062/2?u=lotb

All that is needed is a "not remote_ip" directive

**Comment by ale-rinaldi** [comment]
Hello,

sorry for the delay; however, yes, I would have given the same suggestion you got on the community.

Actually the logic is that Caddy matchers are as pure as possible, each of them only matches what it has to. It's then up to you to combine various matchers to obtain your result; this makes them extremely powerful.

On the other side, having a matcher matching over multiple conditions just makes it harder to configure and understand.

**Comment by m2acgi** [comment]
@ale-rinaldi @allthesebugsv2 How to match `(remote_ip private_ranges) OR (allow_countries FR)` ?
