### ISSUE TITLE
Load module before ratelimit

### ISSUE THREAD

**Issue by celsoft** [porech/caddy-maxmind-geolocation#25]
Hello. I'm using the module github.com/mholt/caddy-ratelimit
Is there any way to filter traffic by geo before it reaches the ratelimit module? Thank you

**Comment by Nindaleth** [comment]
Hi, maybe the [`order`](https://caddyserver.com/docs/caddyfile/options#order) directive is something that could help you? [Here's](https://caddyserver.com/docs/caddyfile/directives#directive-order) the order of the built-in directives (not sure how the additional modules factor into this).

**Comment by celsoft** [comment]
Hello. I was able to achieve the desired result using route.
```
import GEOFILTER
    route {
        import RATELIMIT
        reverse_proxy {$REVERSE_PROXY_IP}:{$REVERSE_PROXY_PORT}
    }
```
