### ISSUE TITLE
Doesn't appear to work currently

### ISSUE THREAD

**Issue by danbritt** [porech/caddy-maxmind-geolocation#5]
Tried to use this to limit connections to US-based IPs only using "allow_countries US" and it blocked me

As a test, I converted the entire list of countries from https://www.geonames.org/countries/ into a space-delimited list and set them on the "deny_countries" config, and it let me access the site.

**Comment by danbritt** [comment]
I got it figured out. It had to do with the environment the app was running in.

I had it hosted using azure kubernetes service, and it was exposed using a LoadBalancer service. By default, the load balancer does not maintain the client/remote IP as it forwards traffic to the caddy container in the kubernetes cluster. So it was coming back with an empty string as the country code when it would do a lookup on the ip address.

To fix this, you have to add a property to the LoadBalancer service configuration in the yml:
```
externalTrafficPolicy: Local
```

I found this info in the docs here: https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard

**Comment by ale-rinaldi** [comment]
Thank you @danbritt ,

this will help people who will have the same issue 👍
